sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        1kKozXtIA9HaHHIjmUR00Nn2rkt/fFmqDQbG1GySyAnfTXr5rCSAujxn/yi6AU7Kv5idxqkKa+z5m9No1UrwhWVLp3C/f8LZ9Pug3Vz1NNvHmKsoBQ/1WIkdCI3AAyKb26c2UOubN5rhXSywWONttc8epaMwe6uGdWqRsKohFz3nOJ/jMJBiTvl/lpIHbyTqlbe03qNBZ7zMxgZ62YQlrs84EctzANi+Cbd3Vg/4dbaar/103oocZ4oiXdgzv24tUaDwb2fGwDkaCA2tKqnPnijEFOXei5b6yBilJSTqRcyA8F65cFUz4ACi1mpstGDQkO+gefvUv+rY2sn+JeV8YgL3o3Kt17vSP+G4JXrDE12gPmmu5upArl9me9bGyxIGno/Iqjv5KqnOMBOYXo6927mZ/cnDKeeMUBpt3JZmb7IVahttvU8ETAFMn6KWiEVVhpr49CqArlJgMckBxlpnDmJbwMDKjzvMdBjQQPDIAvebbJHJ5Dw2nOU9wXxw9Yv2Q3oXLqxdm+3s3oWZEw4eAyaxLbZxLN2ePj3vqseOmu3sNdaAu/2lXIKYNS+daphSbL/6b9idvqyRUeXxTwiM4KoRfYW+AhB857GP/j7s+p4pAasg/0ChJJWAGcvgmjD+CKUziuaqbOH0P70M6nI8OKfiLd+k0sjZ+rhzGz2DuMs=
    - secure: >-
        Sqd/BxBZKTceVUH1wkYsf4XnQXuJ0d3GYyfgSOaY9kEi6maWHZ0k9Jyya/8X8u0Pl2bqiEMprFj2AbKTAKJLE1EueJHkWcbMcKJ9fJbEMuvMjW0C2f6TiHImZAGh13IsfRdyModla+0TsoubP2KoXTtyGyfq6qKr/oZGevYSBu6IQDXe71N3smNwSj7Dvw+MpwkO4kzvqe5RRBDilv3726bGJ7OwOlzVkzHSi8z3V1ox7KbIrt63Yr4u1b7t7V1cNqKFK/NBqyK579m+8cjoSq6FSc8gqnBPMKl7Cwh9CbnEqKRRQ7gKBRdnfzXHoPibi26vpGhXln4o7i9u3VW+IMXUL9liY+HpqrgeoQ3nQvoh1oymr2QDpMQ7A0ktIls/rdLGSYUlm6okJtuGLv2mjACZbRzvn+vYBP8DSKC5f75WLwxt+9FLIDnJroWVMOmUvf96pVq2sMjo9uuqpTvu/DpJZbN4s3nnYoHBPKreGZvr8uXKu0t4a17cvNXW2ZQY/2rWBGSOf+dDjlelS0r8dP32ziYhdwIvLjhSmQnUU3/sGiq3VXm8PwloZ0LvnAqFplaODE4ZoCSjSoLSX4NNMjhdr52zWCpKq9h2CogQUfOywU+CKB5OIsMdGVM/erjRWyBNV5mxXnFDcALkMsLhzfbKYhPB13YrcO1ClbTMbhI=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
