sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        nQ22I9sP024FAnxqYRMQvfW0igvs3Hq2f19RxOaMp2Epk2lHUPJUVfBOZbBnXGt/+yTUBcwvwbAvTGAp41xJBOIBo+8oPIbyr8+oQHVioY2cxcIf1VWzDlei90L2gSGqMySmxYAHUX3iPRUALSZXfCyuzdKppNRl+lgTiAwKEmU4/DJmYZ8dABmNK/Hq+KObQbjlS/6UPlpzR/aQUJgBztRn+aEW+v/dBaL+517NMuRkbOwzznQ0iDF7sBUCFdXlu+TacUXaxvJ+5DDp7AHACp2KgjZcPc8Im8T440GfnNVLH09eZ4lMsg00+YcjlvBTYyb+WXuMgmSGW1oP+ddaLH8xdMTzKOEHwXKIyP5qdJb3bhd6vWPZ6FOa5BPBzYMHHwW/g6f/iyMPTJQmITieRwsGRyEIKpQ0+4G0+Hx1eVBRxtGp4lFYroXXsv2mOrc47kGFyM0K11F9DumdledkKnnRMUNOo4YecmoDwfEGalDIMM0E0LJMzQuMaN9vABLzrWH+HTiahEYWvOyYwNj4ShSASaN/GUs4Oc8bdwQgUfuwALHqCZGi8i7QUrjvqfhj2yyWOI7kz2nASqSBoRw//NuQQXVQEkqcx+9YZo1wZGIe8ouCwYGljh+mpcSH4Zc9NC5vVEYMgU3Eh9z9EoB9cENvUWwnHSDj9Qdqsxs6aQE=
    - secure: >-
        D6/gCVg+huYozoQMjKHmQww2HDgAWmj+0z50Jn3juOTRUgTsHFuY2mYCjt0qit4Kd8xeqfBLZCbs8iceIlFDXeBMQg6UNVfak2Wpf7HE/b6mIApLPwawOuxuNfHayJaLDfMwnsdsJJ4BGTcdbwlVWcmQgwENuUOoD2sOFpR+temKAxQVumV1JNcqs26R9RgeNfNPvYO0GzZKwjSzj3H3MupZCiHcOLy7NeUFI+E/zc6RXr2EoamrF5ye+ALOaeu8mntXXRW6F+BP39XKGcYvfT0A+O2NgGXw+b0Abm77qvKKyW/HWB2kaa60xi1TEtkiIPFW7UJSdYuVNopA982t3MaOId3R0uJuc5XYelESUoSuM0cKJ+cYL2QGpqJgqQy7WCGgE1M/+WbVk3jZob9h8NWYdH3jAzHg6LhY5MREuxIqV4FxwzvyxUq9Vao4cXxnBcjYhkRWm47KsskETRLHiAH8BIouQxKoFA8mzoOdGnEAQijiW6FLd4CZIGS5ICXgh1pFTKIk49OgABr2JT6xAfQEg0WciBrVZopOSAVG/KbGQDUsgqeEGYlyG9pWH8u5F8SGjEVMOPsXrURCHXvI+qlMB8aPxA4w+sTgiKQlMuVWeXKShcsMMgA/176MveA8RuiCKFcJneByrpkrZS3QTp896ZEU2kR0lL6VVLrJqqA=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
