sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        HkzjkhVoKd8NlR+RrDUCtYWsgOUzzdtWGEPPLrc9cj8R5+bQfMRl8b9p4VBYsGs/3PN2w6ZimnB3U1IqpBobm7bd33BoZHMPfcXO74mWmKyPDYnYVWfcgpWHhgtpIJXMLRdgs9lHjY6MizXrDcTcYzzrO9OguXwDabj32q6qmyGXj0WG7szmQF4GoMh6jfJBJ5YFm203IG0rKGxrlAkDsrchc88DKIqlfSMdC1syUY17Qx0ujzhjAR3jN0K6poOLaXK+pdxNlzDRq5Iz/mWl8WynTCEuLGXTXBv/z4JjClP4UAjtXDrIoJsELfraNNs+L6irxgzVTVvyekseZVrgEiNWNHJfGwIo+30Hxfc8aTq5jzqUPT1oyCy3ybfuLP8MzXe6ThCdMXvAgYpAa+Ppq2rbE3/qkTgy4YMYSx90pJtZGCDE1dWLzKSb8fq9RMDSfJEP3Vab+BDts+aaQIe43nxsiowNGz8lzDvkMPlXk/1h0J6sCuQ78c3RUixJ1qNt+ysYYrD228cQUDLvWNeUcsy3X7S3y8u5eNi2R20wvm8EDE0V/eYIFjrwuO4tQ5O9Uk6fPRAwJoA7lqjp9nDig6LUnVQw8hnbXLtqyOXb5t40NQ43l6EcQIa152kVrr5iZif62iVPtKbR41S8pACYecnlzzjzkXtNRs+or5r5bpQ=
    - secure: >-
        UZrki/z8xwjJVhLPyRcLPuly4JiYooidKFyc3e6Uk76eaYJEn4YNytY2uDOCVFwJUiBkUlKElgxQvYncLNyv0vpHAb9z0k6y97HADIdQgJESdTSop75Z3SIyB8Jq5uc0fgy5652sLmaPYp1ZvrpAKpKHttsTfAmpkdb94EcTUwH9zdG7B1Mo0DDjw/LB3uQ8PSf1q3ohx/CoRPDJ/WploL0xe0qn5q5XPCnpHG3BREjbto4Sss5JPpOltIIubcdU0gh/PWBxEV+TLobHcItrKUGsBOZaAkLsrIVTjHhgCzo7U9iVKNWRBLBKbRY/TA+RuJln+o5N9Ed7DY5rcmZaWYJYXfRMnXYlmFCwGLnY+EqzMT4VLfzostwVcnk/Bn4QIDL8jjrl1emrAjIbQ+IIleE4jGHLNQLD+tluHpW6lhI2ma5gcDz3w8UzvPmjWepDsaLBKmzdso8CIZpg9BhlbXEIQeA/pP3s42HhjF5pN0MT+q/S2W3mJY2CguyQLrdfytnhXcs5p752GMVAta5T36qP6x5c9pkUlF8wHY6R/KakIBFuVq/e3Ysv4Bg9fMRqivetcwU9eUokOcADdUaWFpq8sqH1u5/VGqt24rctLCfkRuVbH4QU1t53zPOpNxSJtsgqhWQNhJoz7lvFuW5oxpiZ/wJguhnhdC1vj5ydZJc=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
